version: '3.8' 
services:
  backend:
    image: annotation-tool-ai:latest
    #image: neurobagel/annotation-tool-ai:nightly # dockerhub!!
    container_name: annotation-tool-ai-app
    ports:
      - "9000:9000" # to check if the API is working fine 
    # uncomment the following lines if you want to use GPU  
    # deploy: 
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all


  frontend:
    image: userinterface:latest 
    #image: neurobagel/annotation-tool-ai-ui:nightly # dockerhub!!
    container_name: annotation-tool-userinterface
    ports:
      - "3000:80"  # Map port 80 inside the container to port 3000 on local machine

