name: build docker nightly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push annotation-app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/annotation-tool-ai:nightly

      - name: Build and push annotation-ui
        uses: docker/build-push-action@v6
        with:
          context: ./ui-integration
          file: ./ui-integration/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/annotation-tool-ai-ui:nightly

          